// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnT_shAQzU7JvVj1S7A6O4qkz41zYHnnY',
    appId: '1:14996535157:web:bfd2cdaba2743b28eac53c',
    messagingSenderId: '14996535157',
    projectId: 'invertory-pos',
    authDomain: 'invertory-pos.firebaseapp.com',
    storageBucket: 'invertory-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWdO9wcdAIz4ShQfJH1wGXs9w711JgsQ',
    appId: '1:14996535157:android:d5325f6efe86839feac53c',
    messagingSenderId: '14996535157',
    projectId: 'invertory-pos',
    storageBucket: 'invertory-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7K9EDulDmLzLL1WRAi5VhQHDrkcOoBkk',
    appId: '1:14996535157:ios:978876ede087a47eeac53c',
    messagingSenderId: '14996535157',
    projectId: 'invertory-pos',
    storageBucket: 'invertory-pos.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7K9EDulDmLzLL1WRAi5VhQHDrkcOoBkk',
    appId: '1:14996535157:ios:978876ede087a47eeac53c',
    messagingSenderId: '14996535157',
    projectId: 'invertory-pos',
    storageBucket: 'invertory-pos.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );
}
